.TH SECRET 1

.SH NAME
secret \- send file to specific server through icmp packets

.SH SYNOPSIS
.B secret
<\fB\-s\fR \fIip|hostname\fR>
<\fB\-r\fR \fIsrc_file\fR>
[\fB\-l\fR]

.SH DESCRIPTION
.B secret
sends source file, specified in argument \fB\-r\fR to server specified in argument \fB\-s\fR. File is sended through icmp packets. Program create custom IP and ICMP headers and also specifies custom protocol for file transfer handling. After setting up headers file is sended to checked IP addres with sendto(). Tranfer is not secured, server is not sending any messages back to client. Server verison of program accepts packets, merging data together, decrypt whole file and ave it to current file in witch server runs. Size of tranfered file is limited by RAM of machine, because file is loaded in on unsigned char array.

.RS 5
struct s_icmp_file_info
{
.RS 5
uint8_t 			type
.br
uint32_t			order
.br
int				cipher\_len
.br
int				count
.br
int				part\_size
.br
int				src\_len
.br
unsigned char		iv[IV_LEN]
.br
char				filename[MAX_FILENAME]
.RE
}
.RE

Payload of packets is encrypted via 256-AES in CBC mode. Key lenghth has to be 256 bits long and iv has to be 128 bits long. File is encrypted at once before sending and not part by part for better security. Machine has to have SSL library installed.

Supports both IPv4 and IPv6 servers.

.SH OPTIONS
\fB\-s\fR \fIip|hostname\fR
.br
	Destination IP addres or hostname (localhost, google.com, etc.)

\fB\-r\fR \fIfile\fR
.br
	Source file for transfer to server, doas not depends on filetype

\fB\-l\fR
.br
	Determines if program will run in server mode, absence means client mode and at that time program has to have arguments above, if program starts with this argument, arguments above are not accepted